// <auto-generated />
namespace EF6ClassLibraryFluentAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class mapcolumnandtabletoteacher : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mapcolumnandtabletoteacher));
        
        string IMigrationMetadata.Id
        {
            get { return "201901151112489_map column and table to teacher"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
