// <auto-generated />
namespace EF6ClassLibraryFluentAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class departmentdbsetremove : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(departmentdbsetremove));
        
        string IMigrationMetadata.Id
        {
            get { return "201901151104151_department dbset remove"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
