// <auto-generated />
namespace EF6ClassLibraryFluentAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class departmentdbsetremove3243243 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(departmentdbsetremove3243243));
        
        string IMigrationMetadata.Id
        {
            get { return "201901151105014_department dbset remove3243243"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
